Prettify settings
walkwithchrist/missionary-tools pull request #21
Opened 2021-07-10 22:12 UTC by scottdmilner

Replaces the old JSON settings page with a clean UI

This resolves #12

2021-07-10 22:15 UTC, david3214 commented on appscript/page_interaction/database.js
> +function pullstuff(){
We can remove this function, since it was just used for testing

2021-07-10 22:15 UTC, david3214 commented on appscript/page_interaction/code.js
> +function include(filename){
Would be beneficial to have comments describing the purpose of this function

2021-07-10 22:16 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +      // formatSettings(programSettings)
We can remove this line

2021-07-10 22:17 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +      let formatReverse = this.swap(this.formatList)
Could be a const

2021-07-10 22:20 UTC, david3214 commented on appscript/page_interaction/code.js
> +function include(filename){
It would be beneficial to have this function commented to understand the purpose of it

2021-07-10 22:22 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +      let [toHide, toMerge] = this.statusList.reduce((total, status) => {
Can switch to const

2021-07-10 22:25 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +        else
Should be able to remove, is a use case that will never be hit

2021-07-10 22:27 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +        if (this.addUnitName && !this.unitList.find(unit => unit.name == this.selectedUnit)) {
Check logic, this should be disabling duplicate units

2021-07-10 22:27 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +        else
Should be an impossible use case. can remove

2021-07-10 22:29 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +      } else if (type == 'merge' && this.selectedStatus != 'Add a status') {
Can remove second check for selectedStatus being Add a Status, because the merge box no longer shows up when add a status is a thing

2021-07-10 22:29 UTC, david3214 commented on appscript/page_interaction/settings-script.html
> +      } else if (type == 'hide' && this.selectedStatus != 'Add a status') {
Can remove second check for selectedStatus being Add a Status, because the hide box no longer shows up when add a status is a thing

2021-07-10 22:31 UTC, david3214 commented on appscript/page_interaction/settings-style.html
> +#app {
I would recommend adding a few comments to anything special in here being done with the styling. for example hiding checkbox's or color pickers etc

2021-07-10 22:33 UTC, david3214 commented on appscript/page_interaction/settings.html
> +    <!-- <textarea style="display: block; margin-bottom:10px;" cols="50" rows="25" v-model="programSettings" placeholder="Adjust program settings here"></textarea> -->
We can remove this

2021-07-10 22:33 UTC, david3214 commented on appscript/page_interaction/settings.html
> +        <!-- <label for="page-select">Select a page:  </label> -->
We can remove this

2021-07-10 22:34 UTC, david3214 commented on appscript/page_interaction/settings.html
> +    <!-- <br>
We can remove this comment

2021-07-10 22:35 UTC, david3214 requested changes
A few small cleanup items before we push to master

2021-07-12 23:42 UTC, scottdmilner commented on appscript/page_interaction/database.js
> +function pullstuff(){
Removed

2021-07-12 23:44 UTC, scottdmilner commented on appscript/page_interaction/settings-script.html
> +      // formatSettings(programSettings)
Done

2021-07-12 23:47 UTC, scottdmilner commented on appscript/page_interaction/settings-script.html
> +      let formatReverse = this.swap(this.formatList)
Done

2021-07-12 23:49 UTC, scottdmilner commented on appscript/page_interaction/code.js
> +function include(filename){
Done

2021-07-13 00:18 UTC, scottdmilner commented on appscript/page_interaction/settings-script.html
> +      let [toHide, toMerge] = this.statusList.reduce((total, status) => {
Fixed this and bug in formatData

2021-07-13 00:24 UTC, scottdmilner commented on appscript/page_interaction/settings-script.html
> +        if (this.addUnitName && !this.unitList.find(unit => unit.name == this.selectedUnit)) {
Logic fixed

2021-07-13 00:24 UTC, scottdmilner commented on appscript/page_interaction/settings-script.html
> +        else
Done

2021-07-13 01:02 UTC, scottdmilner reviewed
Issues commented by @david3214 have been fixed

2021-07-13 01:35 UTC, merged